// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.Data;

#nullable disable

namespace MinimalAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240904123941_Initial Creation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvaliable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "J.K. Rowling",
                            Description = "The first book in the Harry Potter series. Introducing the young wizard Harry Potter.",
                            Genre = "Fantasy",
                            IsAvaliable = true,
                            Title = "Harry Potter and the Sorcerer's Stone",
                            YearOfRelease = 1997
                        },
                        new
                        {
                            BookID = 2,
                            Author = "George R.R. Martin",
                            Description = "The first book in the A Song of Ice and Fire series, where the struggle for the Iron Throne begins",
                            Genre = "Fantasy",
                            IsAvaliable = false,
                            Title = "A Game of Thrones",
                            YearOfRelease = 1996
                        },
                        new
                        {
                            BookID = 3,
                            Author = "J.R.R. Tolkien",
                            Description = "The first book in the Lord of the Rings trilogy, where the journey of the One Ring begins.",
                            Genre = "Fantasy",
                            IsAvaliable = true,
                            Title = "The Fellowship of the Ring",
                            YearOfRelease = 1954
                        },
                        new
                        {
                            BookID = 4,
                            Author = "F. Scott Fitzgerald",
                            Description = "A novel that critiques the American dream through the tragic story of Jay Gatsby",
                            Genre = "Classic Fiction",
                            IsAvaliable = true,
                            Title = "The Great Gatsby",
                            YearOfRelease = 1925
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
